name: Code Coverage
on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: github.event_name != 'merge_group'

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true
          submodules: true

      - uses: swatinem/rust-cache@v2

      - name: fetch Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "stable"

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Measure coverage
        run: ./admin/coverage --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
